version: "3.7"
services:
  app:
    ports:
      - "3000:3000"
    build:
      context: app
      dockerfile: docker/prod/Dockerfile
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./app/.env.local

  app-postgres:
    image: postgres:14-alpine
    volumes:
      - app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "54321:5432"

  app-redis:
    image: redis:6.2.6
    ports:
      - "63791:6379"

volumes:
  app-postgres: