version: "3.7"
services:
  app:
    ports:
      - "3001:3001"
    build:
      context: app
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
      - ./app/.next:/usr/src/app/.next
    env_file:
      - ./app/.env.local

  app-postgres:
    image: postgres:14-alpine
    volumes:
      - app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: red
    ports:
      - "54321:5432"

  app-redis:
    image: redis:6.2.6
    ports:
      - "63791:6379"

volumes:
  app-postgres: